# Generated by Django 3.0.6 on 2020-09-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20180423_0727'),
        ('profiles', '0011_accountstatus_user_name'),
    ]

    operations = [
    ]
